# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KMS.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

from qfluentwidgets import PushButton


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(392, 72)
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        Form.setFont(font)
        self.Windows_Pro_Btn = PushButton(Form)
        self.Windows_Pro_Btn.setGeometry(QtCore.QRect(200, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Windows_Pro_Btn.setFont(font)
        self.Windows_Pro_Btn.setObjectName("Windows_Pro_Btn")
        self.Windows_Home_Btn = PushButton(Form)
        self.Windows_Home_Btn.setGeometry(QtCore.QRect(10, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Windows_Home_Btn.setFont(font)
        self.Windows_Home_Btn.setObjectName("Windows_Home_Btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle("KMS啟動工具 By Zhuzi")
        self.Windows_Pro_Btn.setText(_translate("Form", "啟用Windows專業版"))
        self.Windows_Home_Btn.setText(_translate("Form", "啟用Windows家用版"))

    def WinHomeButtonClick(self):
        os.system("slmgr /ipk TX9XD-98N7V-6WMQ6-BX7FG-H8Q99")
        os.system("slmgr /skms kms.loli.beer")

    def WinProButtonClick(self):
        os.system("slmgr /ipk W269N-WFGWX-YVC9B-4J6C9-T83GX")
        os.system("slmgr /skms kms.loli.beer")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
